title: Control Freak
# description: A collection of mathematical notes and topics
baseurl: "/math-draft"
url: "https://dimos.github.io"
theme: minima           
kramdown:
  math_engine: mathjax
  math_engine_opts:
    preview: true
    preview_as_code: false
  input: GFM
  syntax_highlighter: rouge

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap

# Exclude from processing
exclude:
  - README.md
  - .gitignore
  - .git/
  - Gemfile
  - Gemfile.lock

# Include files that start with underscore
include:
  - _pages

# Header navigation configuration
header_pages: []

# Exclude topic pages from navigation
exclude_from_nav:
  - topics/